// sample data for the app

// re-export types so pages can import from here too
export type { User, Venue, Booking, Application, VendorComment, ComplianceDocument } from "./types";

import type { User, Venue, Booking, Application, VendorComment } from "./types";

// sample users - 3 hirers and 3 vendors
export const DEFAULT_USERS: User[] = [
  // hirers
  {
    id: "1",
    email: "taylorswift@gmail.com",
    password: "Password/101",
    role: "hirer",
    firstName: "Taylor",
    lastName: "Swift",
    phone: "0412 847 293",
  },
  {
    id: "2",
    email: "beyonce@gmail.com",
    password: "Password/102",
    role: "hirer",
    firstName: "Beyonce",
    lastName: "Knowels",
    phone: "0431 562 718",
  },
  {
    id: "3",
    email: "arianagrande@gmail.com",
    password: "Password/103",
    role: "hirer",
    firstName: "Ariana",
    lastName: "Grande",
    phone: "0458 193 047",
  },

  // vendors
  {
    id: "4",
    email: "harrystyles@gmail.com",
    password: "Password/104",
    role: "vendor",
    firstName: "Harry",
    lastName: "Styles",
    phone: "0477 823 154",
  },
  {
    id: "5",
    email: "mileycyrus@gmail.com",
    password: "Password/105",
    role: "vendor",
    firstName: "Miley",
    lastName: "Cyrus",
    phone: "0493 217 865",
  },
  {
    id: "6",
    email: "justinbieber@gmail.com",
    password: "Password/106",
    role: "vendor",
    firstName: "Justin",
    lastName: "Bieber",
    phone: "0426 391 574",
  },
];

// 9 venues total, 3 per vendor
export const DEFAULT_VENUES: Venue[] = [
  // Harry Styles venues
  {
    id: "v1",
    vendorId: "4",
    name: "The Glasshouse Pavilion South Wharf",
    location: "South Wharf, Melbourne VIC 3006",
    capacity: 250,
    pricePerDay: 4800,
    rating: 4.7,
    reviewCount: 34,
    shortDescription:
      "A stunning all-glass pavilion overlooking the Yarra River. Floor-to-ceiling windows, a private waterfront terrace, and full in-house catering make this perfect for corporate events and conferences.",
    imageUrl: "/TheGlasshousePavilionSouthWharf.jpg",
    amenities: [
      "Full in-house catering kitchen",
      "Private waterfront terrace",
      "Built-in AV system and projector",
      "Free high-speed WiFi",
      "Air conditioning and heating",
      "Dedicated event coordinator",
      "Wheelchair accessible",
      "Valet parking available",
    ],
    suitabilityTags: ["Corporate", "Conference", "Gala Dinner"],
    availabilityStatus: "Available",
  },

  {
    id: "v2",
    vendorId: "4",
    name: "Rooftop Garden Terrace at One Southbank",
    location: "Southbank, Melbourne VIC 3006",
    capacity: 75,
    pricePerDay: 2200,
    rating: 4.9,
    reviewCount: 18,
    shortDescription:
      "On the 14th floor with panoramic CBD and Yarra River views. Wrapped in lush greenery and warm string lights, this intimate rooftop terrace is a magical setting for weddings and exclusive evening events.",
    imageUrl: "/RooftopGardenTerraceatOneSouthbank.jpg",
    amenities: [
      "Private lift access",
      "String light canopy setup",
      "Bar service included",
      "Cocktail furniture and lounge seating",
      "Outdoor heaters for cooler nights",
      "Built-in sound system",
      "Photography-friendly ambient lighting",
    ],
    suitabilityTags: ["Wedding", "Gala Dinner"],
    availabilityStatus: "Limited Availability",
  },

  {
    id: "v3",
    vendorId: "4",
    name: "Federation Grand Ballroom",
    location: "Melbourne CBD, Melbourne VIC 3000",
    capacity: 480,
    pricePerDay: 9200,
    rating: 4.6,
    reviewCount: 51,
    shortDescription:
      "Melbourne's most iconic restored heritage ballroom with original ornate ceilings, crystal chandeliers, and Carrara marble floors. Opens onto a private courtyard garden. Seats up to 480 guests banquet-style.",
    imageUrl: "/FederationGrandBallroom.jpg",
    amenities: [
      "Original crystal chandeliers",
      "Ornate heritage interior (1920s)",
      "Private courtyard garden",
      "Two adjacent breakout rooms",
      "Grand piano available on request",
      "Full commercial kitchen and bar",
      "On-site parking for 80 vehicles",
      "Accessibility ramps at all entry points",
    ],
    suitabilityTags: ["Wedding", "Gala Dinner", "Corporate", "Conference"],
    availabilityStatus: "Available",
  },

  // Miley Cyrus venues
  {
    id: "v4",
    vendorId: "5",
    name: "The Brunswick St Warehouse Studio",
    location: "Fitzroy, Melbourne VIC 3065",
    capacity: 110,
    pricePerDay: 2600,
    rating: 4.8,
    reviewCount: 29,
    shortDescription:
      "A raw converted 1940s textile warehouse on iconic Brunswick Street. Exposed brick, original timber floors, and a full professional stage make this ideal for product launches, creative showcases, and intimate corporate events.",
    imageUrl: "/TheBrunswickStWarehouseStudio.jpg",
    amenities: [
      "Professional stage (8m x 5m)",
      "Full LED and spotlight lighting rig",
      "Built-in PA sound system",
      "Green room and backstage area",
      "Original exposed brick and timber floors",
      "Free street parking nearby",
      "Kitchenette and bar area",
      "Loading dock access for equipment",
    ],
    suitabilityTags: ["Corporate", "Conference"],
    availabilityStatus: "Available",
  },

  {
    id: "v5",
    vendorId: "5",
    name: "Bayside Marquee at St Kilda Esplanade",
    location: "St Kilda, Melbourne VIC 3182",
    capacity: 190,
    pricePerDay: 3800,
    rating: 4.5,
    reviewCount: 42,
    shortDescription:
      "A premium climate-controlled marquee set directly on the St Kilda Esplanade with uninterrupted Port Phillip Bay views. Retractable walls transition between indoor and outdoor settings with a dedicated dance floor included.",
    imageUrl: "/BaysideMarqueeatStKildaEsplanade.jpg",
    amenities: [
      "Retractable walls for indoor/outdoor flow",
      "Dedicated hardwood dance floor",
      "Separate cocktail lounge area",
      "Full on-site catering kitchen",
      "Bay-view terrace",
      "Valet parking service",
      "Private bridal preparation suite",
      "Air conditioning and heating year-round",
    ],
    suitabilityTags: ["Wedding", "Gala Dinner"],
    availabilityStatus: "Available",
  },

  {
    id: "v6",
    vendorId: "5",
    name: "Carlton Heritage Meeting Rooms",
    location: "Carlton, Melbourne VIC 3053",
    capacity: 55,
    pricePerDay: 1350,
    rating: 4.3,
    reviewCount: 16,
    shortDescription:
      "Three connected meeting rooms inside a beautifully preserved 1880s bluestone building near Melbourne University. Original lead-light windows and polished floorboards create a sophisticated conference setting without the corporate blandness.",
    imageUrl: "/CarltonHeritageMeetingRooms.jpg",
    amenities: [
      "Three flexible room configurations",
      "Lead-light heritage windows",
      "Whiteboard and flip chart stands",
      "Tea and coffee station included",
      "High-speed fibre WiFi",
      "Breakout lounge area",
      "Tram stop directly outside",
      "Catering delivery accepted on-site",
    ],
    suitabilityTags: ["Conference", "Corporate"],
    availabilityStatus: "Limited Availability",
  },

  // Justin Bieber venues
  {
    id: "v7",
    vendorId: "6",
    name: "Yarra Valley Harvest Estate",
    location: "Yering, Yarra Valley VIC 3770",
    capacity: 340,
    pricePerDay: 6800,
    rating: 4.9,
    reviewCount: 63,
    shortDescription:
      "Set among 12 hectares of working vineyard and English gardens, 55 minutes from Melbourne CBD. Includes a 1920s sandstone homestead, a glass event pavilion, an outdoor ceremony lawn with mountain views, and accommodation for 28 guests.",
    imageUrl: "/YarraValleyHarvestEstate.jpg",
    amenities: [
      "12-hectare working vineyard estate",
      "1920s sandstone homestead",
      "Floor-to-ceiling glass event pavilion",
      "Outdoor ceremony lawn with mountain views",
      "On-site accommodation for 28 guests",
      "Wine and barrel room access",
      "In-house catering using estate produce",
      "Full lighting and AV package included",
    ],
    suitabilityTags: ["Wedding", "Gala Dinner", "Corporate"],
    availabilityStatus: "Available",
  },

  {
    id: "v8",
    vendorId: "6",
    name: "Collingwood Factory Loft",
    location: "Collingwood, Melbourne VIC 3066",
    capacity: 90,
    pricePerDay: 1950,
    rating: 4.4,
    reviewCount: 23,
    shortDescription:
      "Top floor of a converted 1960s factory building in Collingwood. 4.5-metre ceilings, polished concrete floors, and original factory windows give the space a raw, authentic character popular for creative workshops and intimate corporate gatherings.",
    imageUrl: "/CollingwoodFactoryLoft.jpg",
    amenities: [
      "4.5m high ceilings throughout",
      "Polished concrete floors",
      "Original factory windows (north-facing light)",
      "Full-wall whiteboard surface",
      "Kitchenette and drinks fridge",
      "Rooftop terrace access for breaks",
      "Unlimited high-speed WiFi",
      "Freight elevator for heavy equipment",
    ],
    suitabilityTags: ["Corporate", "Conference"],
    availabilityStatus: "Available",
  },

  {
    id: "v9",
    vendorId: "6",
    name: "Port Melbourne Waterfront Pavilion",
    location: "Port Melbourne, Melbourne VIC 3207",
    capacity: 210,
    pricePerDay: 5400,
    rating: 4.7,
    reviewCount: 38,
    shortDescription:
      "A striking contemporary pavilion built over the water at Port Melbourne with 270-degree bay views through floor-to-ceiling glass. The private marina jetty allows guest arrivals by water taxi. Ideal for high-profile product launches and waterfront wedding receptions.",
    imageUrl: "/PortMelbourneWaterfrontPavilion.jpg",
    amenities: [
      "270-degree Port Phillip Bay views",
      "Private marina jetty for water taxi arrivals",
      "In-house executive chef and kitchen team",
      "Full bar service",
      "Built-in AV system and intelligent lighting",
      "Heated and cooled throughout",
      "Complimentary parking for 60 cars",
      "Dedicated event manager on the day",
    ],
    suitabilityTags: ["Corporate", "Wedding", "Gala Dinner"],
    availabilityStatus: "Available",
  },
];

// 11 bookings across the 3 hirers
export const DEFAULT_BOOKINGS: Booking[] = [
  // Taylor Swift bookings
  {
    id: "b1",
    hirerId: "1",
    venueId: "v3",
    venueName: "Federation Grand Ballroom",
    venueLocation: "Melbourne CBD, Melbourne VIC 3000",
    eventName: "Annual Marketing Summit 2025",
    eventDate: "2025-08-15",
    vendorRating: 5,
    status: "Completed",
  },
  {
    id: "b2",
    hirerId: "1",
    venueId: "v7",
    venueName: "Yarra Valley Harvest Estate",
    venueLocation: "Yering, Yarra Valley VIC 3770",
    eventName: "Company Retreat Weekend",
    eventDate: "2025-11-22",
    vendorRating: 4,
    status: "Completed",
  },
  {
    id: "b3",
    hirerId: "1",
    venueId: "v1",
    venueName: "The Glasshouse Pavilion South Wharf",
    venueLocation: "South Wharf, Melbourne VIC 3006",
    eventName: "Product Launch - Swift Creative Co.",
    eventDate: "2026-03-08",
    vendorRating: 5,
    status: "Completed",
  },
  {
    id: "b4",
    hirerId: "1",
    venueId: "v5",
    venueName: "Bayside Marquee at St Kilda Esplanade",
    venueLocation: "St Kilda, Melbourne VIC 3182",
    eventName: "End of Financial Year Gala 2026",
    eventDate: "2026-06-28",
    vendorRating: 0,
    status: "Active",
  },

  // Beyonce bookings
  {
    id: "b5",
    hirerId: "2",
    venueId: "v4",
    venueName: "The Brunswick St Warehouse Studio",
    venueLocation: "Fitzroy, Melbourne VIC 3065",
    eventName: "Charity Fundraiser Night",
    eventDate: "2025-07-19",
    vendorRating: 4,
    status: "Completed",
  },
  {
    id: "b6",
    hirerId: "2",
    venueId: "v9",
    venueName: "Port Melbourne Waterfront Pavilion",
    venueLocation: "Port Melbourne, Melbourne VIC 3207",
    eventName: "Brand Launch: Ivy Solutions",
    eventDate: "2025-09-04",
    vendorRating: 5,
    status: "Completed",
  },
  {
    id: "b7",
    hirerId: "2",
    venueId: "v2",
    venueName: "Rooftop Garden Terrace at One Southbank",
    venueLocation: "Southbank, Melbourne VIC 3006",
    eventName: "Team Appreciation Evening",
    eventDate: "2025-12-11",
    vendorRating: 5,
    status: "Completed",
  },
  {
    id: "b8",
    hirerId: "2",
    venueId: "v6",
    venueName: "Carlton Heritage Meeting Rooms",
    venueLocation: "Carlton, Melbourne VIC 3053",
    eventName: "Quarterly Strategy Workshop",
    eventDate: "2026-04-30",
    vendorRating: 0,
    status: "Active",
  },

  // Ariana bookings
  {
    id: "b9",
    hirerId: "3",
    venueId: "v8",
    venueName: "Collingwood Factory Loft",
    venueLocation: "Collingwood, Melbourne VIC 3066",
    eventName: "UX Design Sprint Workshop",
    eventDate: "2025-10-03",
    vendorRating: 3,
    status: "Completed",
  },
  {
    id: "b10",
    hirerId: "3",
    venueId: "v7",
    venueName: "Yarra Valley Harvest Estate",
    venueLocation: "Yering, Yarra Valley VIC 3770",
    eventName: "Staff End of Year Celebration",
    eventDate: "2025-12-13",
    vendorRating: 5,
    status: "Completed",
  },
  {
    id: "b11",
    hirerId: "3",
    venueId: "v3",
    venueName: "Federation Grand Ballroom",
    venueLocation: "Melbourne CBD, Melbourne VIC 3000",
    eventName: "Grande & Associates Annual Awards Night",
    eventDate: "2026-07-22",
    vendorRating: 0,
    status: "Active",
  },
];

// sample applications - 4 total v4 
export const DEFAULT_APPLICATIONS: Application[] = [
  {
    id: "a1",
    hirerId: "1",
    venueId: "v9",
    venueName: "Port Melbourne Waterfront Pavilion",
    eventName: "Swift Creative Co. End of Year Awards 2026",
    eventType: "Gala Dinner",
    eventDate: "2026-11-14",
    guestCount: 180,
    additionalNotes:
      "We are hosting our annual company awards night and need dedicated AV support for a short film screening and live award presentations.",
    reputationTags: ["Timely payer", "Good communicator", "Professional setup"],
    status: "Pending",
    submittedAt: "2026-04-02",
  },
  {
    id: "a2",
    hirerId: "1",
    venueId: "v3",
    venueName: "Federation Grand Ballroom",
    eventName: "Annual Marketing Industry Conference",
    eventType: "Conference",
    eventDate: "2026-09-06",
    guestCount: 420,
    additionalNotes:
      "Full-day conference with three keynote speakers, a panel session, and a networking lunch. Will require on-site catering coordination.",
    reputationTags: ["Timely payer", "Good communicator", "No prior incidents", "Insured events"],
    status: "Pending",
    submittedAt: "2026-03-15",
  },
  {
    id: "a3",
    hirerId: "2",
    venueId: "v7",
    venueName: "Yarra Valley Harvest Estate",
    eventName: "Knowles Foundation Annual Gala Dinner",
    eventType: "Gala Dinner",
    eventDate: "2026-10-18",
    guestCount: 290,
    additionalNotes:
      "Fundraising gala for the Knowles Foundation. We require vineyard-inspired table styling and would like to discuss a set menu with the in-house chef team.",
    reputationTags: ["Good communicator", "Professional setup", "Insured events"],
    status: "Declined",
    submittedAt: "2026-03-28",
  },
  {
    id: "a4",
    hirerId: "3",
    venueId: "v5",
    venueName: "Bayside Marquee at St Kilda Esplanade",
    eventName: "Grande & Associates Summer Networking Evening",
    eventType: "Corporate",
    eventDate: "2026-12-05",
    guestCount: 150,
    additionalNotes:
      "Cocktail-style networking event for around 150 professionals in the architecture and interior design industry. Looking for standing cocktail furniture setup with bay view access.",
    reputationTags: ["Timely payer", "No prior incidents"],
    status: "Pending",
    submittedAt: "2026-04-08",
  },
  // Additional applications to provide more data for the infographic report page (UM4)
  {
    id: "a5",
    hirerId: "2",
    venueId: "v2",
    venueName: "Rooftop Garden Terrace at One Southbank",
    eventName: "Beyonce Entertainment Group Milestone Celebration",
    eventType: "Gala Dinner",
    eventDate: "2026-11-10",
    guestCount: 65,
    additionalNotes:
      "Intimate gala celebration on the rooftop with panoramic CBD views. Expecting executive attendees and key industry partners. Requested string light setup and champagne service throughout the evening.",
    reputationTags: ["Timely payer", "Good communicator", "Insured events"],
    status: "Pending",
    submittedAt: "2026-04-05",
  },
  {
    id: "a6",
    hirerId: "1",
    venueId: "v4",
    venueName: "The Brunswick St Warehouse Studio",
    eventName: "Swift Creative Co. Workshop Series Launch",
    eventType: "Corporate",
    eventDate: "2026-08-22",
    guestCount: 95,
    additionalNotes:
      "Product workshop launch for 90-100 creative professionals. Need stage setup for live demonstrations and breakout room access for smaller discussion groups. Professional stage lighting is essential.",
    reputationTags: ["Timely payer", "Professional setup", "Good communicator"],
    status: "Pending",
    submittedAt: "2026-04-09",
  },
  {
    id: "a7",
    hirerId: "3",
    venueId: "v8",
    venueName: "Collingwood Factory Loft",
    eventName: "Ariana Grande Ventures Portfolio Review",
    eventType: "Corporate",
    eventDate: "2026-10-15",
    guestCount: 80,
    additionalNotes:
      "Portfolio review event for startup founders and venture capital partners. Require high-speed WiFi for tech demos, projector setup for presentations, and rooftop terrace access for networking breaks.",
    reputationTags: ["Good communicator", "No prior incidents", "Professional setup"],
    status: "Pending",
    submittedAt: "2026-04-06",
  },
  {
    id: "a8",
    hirerId: "2",
    venueId: "v6",
    venueName: "Carlton Heritage Meeting Rooms",
    eventName: "Beyonce Ventures Board Strategy Meeting",
    eventType: "Corporate",
    eventDate: "2026-09-14",
    guestCount: 45,
    additionalNotes:
      "Quarterly board meeting for our investment portfolio committee. Need quiet, professional setting with high-speed WiFi and breakout lounge for 1-on-1 partner meetings.",
    reputationTags: ["Timely payer", "Good communicator", "Professional setup"],
    status: "Pending",
    submittedAt: "2026-04-07",
  },
  {
    id: "a9",
    hirerId: "3",
    venueId: "v1",
    venueName: "The Glasshouse Pavilion South Wharf",
    eventName: "Ariana Grande Foundation Gala Reception",
    eventType: "Gala Dinner",
    eventDate: "2026-11-28",
    guestCount: 220,
    additionalNotes:
      "Charity gala reception for the Ariana Grande Foundation supporting emerging artists and creatives. Waterfront setting preferred, full catering coordination required.",
    reputationTags: ["Timely payer", "Good communicator", "Insured events"],
    status: "Pending",
    submittedAt: "2026-04-10",
  },
];

// vendor comments about hirers
export const DEFAULT_VENDOR_COMMENTS: VendorComment[] = [
  {
    id: "vc1",
    vendorId: "4",
    hirerId: "1",
    hirerName: "Taylor Swift",
    commentText:
      "Taylor was an absolute pleasure to work with throughout the entire booking process. Payment was processed within 24 hours of invoice, all setup requirements were clearly communicated in advance, and the event ran without a single issue. Would welcome them back without hesitation.",
    credibilityTag: "Excellent",
    date: "2026-03-09",
  },
  {
    id: "vc2",
    vendorId: "5",
    hirerId: "2",
    hirerName: "Beyonce Knowels",
    commentText:
      "Beyonce's team was well-organised and professional throughout. There was one minor delay in confirming the final guest count but it was resolved within the same afternoon. The event itself was a great success and the venue was left in excellent condition.",
    credibilityTag: "Good",
    date: "2025-07-22",
  },
];
